
# Build matrix
language: node_js

# Environment variables
env:
  global:
    - CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)

# cache the node modules
cache:
  directories:
    - node_modules
    - "$HOME/.npm"

# Restrict builds on branches
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

# build notification
notifications:
  email:
    - fed-systems@springernature.com
  slack:
    secure: IuzH6deMfNVaPujvbWt+kXk6AAuX0z3FvPsWeHTPNPT1F25ITFKAObxbgTJ6qhxmm5bJRENE0EyrC+z/J0Je0opt7cA8V5/HCt40S/uxYNZ/JqVADWi2mdLJwi9Ysb2ulED4wn2dk4/HJXglLryaiY/+mCCEZLA+4dvktfBXrnzbgnBwtSowYD/fRAsRES1Ga/n3K18rg6YF68U6r/CyAmv26wq/J36ZtON3yjFmWugSzVtF3fTu1dRMDC+O4JJRH2GyGzlj+OM1aaPOF0oEyQaWsbsdnHEwIbKcqR/xKhFePWPdcn/Hvm1/uF/Yxix0FMPU3+AFsyNwYVbM3C/VfcdI4F4kNRJfRfuPpCkRQafJkOXZJdQgE+NP4NzwZ9FdbVrtb/sl8WTvBjaoRAmSFHyWZ3VZ+nNiOF7634LFkXjhR+iKh9IFvhhnluA5st2mQxOZyJjUFsESetz8yQtLhNkreu3Y/+xrkl3SgdyPlHsfB3FOjFfrTQl637iLBpDPJ0kOKjsiPJIMQ+gS+4wy3+9j4HianZSd8dKPkZBONguS6ykGecjYlhriuzezm4QxJBILfYSs37gGEPFigDrrBx78DHqFEfQWHQsannkf+fKtenLfRxCg3dt4gQ8m2jik3ZLeE9czOhCBIaZMGohuvXynvUbRwP1x1N38CTfNS4k=

script:
  - npm run bootstrap && npm run build:ci

# Auto-publish after script
after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then PUBLISH_PACKAGE=true; else PUBLISH_PACKAGE=false; fi'
  - 'echo "Pull Request: $TRAVIS_PULL_REQUEST" && echo "Node: $TRAVIS_NODE_VERSION" && echo "Publish? $PUBLISH_PACKAGE"'
  - 'if [ $PUBLISH_PACKAGE = "true" ]; then npm run publish; fi'
